#!/usr/bin/env bash
# This script display "Best School" 10 times but 9th iteration, displays Hi
i=1
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i == 9 ]; then
	echo "Hi"
    fi
    ((i++))
done
