#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements (resolves two ips)
cp /etc/hosts ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sed -i s/^127.0.0.1/127.0.0.2/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
